export const EXIT_CODES = {
  SUCCESS: 0,
  GENERAL_ERROR: 1,
  VALIDATION_ERROR: 2,
  AUTH_ERROR: 3,
  PERMISSION_ERROR: 4,
  NOT_FOUND: 5,
  NETWORK_ERROR: 10,
  TIMEOUT_ERROR: 11,
  RATE_LIMITED: 12,
} as const;
