export const EXIT_CODES = {
  AUTH_ERROR: 3,
  CONFIG_ERROR: 6,
  GENERAL_ERROR: 1,
  NETWORK_ERROR: 10,
  NOT_FOUND: 5,
  PERMISSION_ERROR: 4,
  RATE_LIMITED: 12,
  SUCCESS: 0,
  TIMEOUT_ERROR: 11,
  VALIDATION_ERROR: 2,
} as const;
