import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import type { Command } from "commander";
import { runAction } from "@/lib/command.js";
import { loadProjectConfig, type ProjectConfig } from "@/lib/config.js";
import { withExamples } from "@/lib/output.js";
import { ENV_NAMES, SERVICE_KEYS } from "@/lib/project.js";
import { theme } from "@/output/theme.js";

export const DEFAULT_TYPES_OUT = "src/frontal-configuration.d.ts";
export const GENERATED_HEADER = "// Generated by frontal types — do not edit.";

function literal(value: string): string {
  return JSON.stringify(value);
}

function union(values: readonly string[]): string {
  return values.length === 0 ? "never" : values.map(literal).join(" | ");
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function keyLine(key: string, type: string, optional = false): string {
  const safeKey = IDENTIFIER.test(key) ? key : literal(key);
  return `  ${safeKey}${optional ? "?" : ""}: ${type};`;
}

/**
 * Renders the `.d.ts` for a project. Purely type-level: service clients are
 * referenced through `import("@frontal-labs/sdk").Frontal`, so the output
 * compiles against the installed SDK without any runtime import.
 */
export function renderTypes(config: ProjectConfig, sources: string[]): string {
  const services = Object.keys(config.services).sort();
  const vars = Object.keys(config.vars).sort();
  const secrets = [...config.secrets.required].sort();

  const lines: string[] = [
    GENERATED_HEADER,
    `// Source: ${sources.join(" + ")}`,
    "",
    'type FrontalSdk = import("@frontal-labs/sdk").Frontal;',
    "",
    `export type FrontalEnvName = ${union(ENV_NAMES)};`,
    `export type FrontalServiceName = ${union(services)};`,
    `export type FrontalKnownService = ${union(SERVICE_KEYS)};`,
    "",
    "/** Plain configuration values from `vars` in frontal.jsonc. */",
    "export interface FrontalVars {",
    ...vars.map((key) => keyLine(key, "string")),
    "}",
    "",
    "/** Secrets that must be present in the environment (`secrets.required`). */",
    "export interface FrontalSecrets {",
    ...secrets.map((key) => keyLine(key, "string")),
    "}",
    "",
    "/** Environment variables a Frontal app can rely on at runtime. */",
    "export interface FrontalEnv extends FrontalVars, FrontalSecrets {",
    keyLine("FRONTAL_ENV", "FrontalEnvName", true),
    keyLine("FRONTAL_API_URL", "string", true),
    "}",
    "",
    "/** Services enabled in frontal.jsonc and their SDK clients. */",
    "export interface FrontalServices {",
    ...services.map((key) =>
      keyLine(
        key,
        `{ remote: ${config.services[key]?.remote ? "true" : "false"}; client: FrontalSdk[${literal(key)}] }`
      )
    ),
    "}",
    "",
    "/** The validated frontal.jsonc for this project. */",
    "export interface FrontalProject {",
    keyLine("name", literal(config.name)),
    keyLine("env", "FrontalEnvName"),
    keyLine("apiUrl", "string"),
    keyLine("services", "FrontalServices"),
    keyLine("vars", "FrontalVars"),
    keyLine("secrets", "{ required: (keyof FrontalSecrets)[] }"),
    "}",
    "",
    "declare global {",
    "  namespace NodeJS {",
    "    // biome-ignore lint/suspicious/noEmptyInterface: augmentation",
    "    interface ProcessEnv extends FrontalEnv {}",
    "  }",
    "}",
    "",
  ];
  return lines.join("\n");
}

export interface TypesResult {
  changed: boolean;
  out: string;
  secrets: string[];
  services: string[];
  vars: string[];
}

export async function generateTypes(options: {
  cwd?: string;
  env?: string;
  out?: string;
}): Promise<TypesResult> {
  const { config, files, root } = await loadProjectConfig({
    cwd: options.cwd,
    env: options.env,
  });
  const out = resolve(root, options.out ?? DEFAULT_TYPES_OUT);
  const content = renderTypes(
    config,
    files.map((file) => relative(root, file))
  );

  const previous = existsSync(out) ? readFileSync(out, "utf-8") : undefined;
  const changed = previous !== content;
  if (changed) {
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, content);
  }

  return {
    changed,
    out,
    secrets: [...config.secrets.required].sort(),
    services: Object.keys(config.services).sort(),
    vars: Object.keys(config.vars).sort(),
  };
}

export function registerTypesCommand(program: Command): void {
  withExamples(
    program
      .command("types")
      .description("Generate TypeScript typings from frontal.jsonc")
      .option("--out <file>", "Output file", DEFAULT_TYPES_OUT)
      .action((opts: { out?: string }, cmd) =>
        runAction(cmd, async ({ fmt, globalOpts }) => {
          const result = await generateTypes({
            env: globalOpts.env,
            out: opts.out,
          });

          if (globalOpts.json) {
            fmt.raw(result);
            return;
          }
          const rel = relative(process.cwd(), result.out) || result.out;
          console.log(
            `${result.changed ? theme.success("write") : theme.dim("up-to-date")}  ${rel}`
          );
          console.log(
            theme.dim(
              `services: ${result.services.join(", ") || "-"} | vars: ${result.vars.length} | secrets: ${result.secrets.length}`
            )
          );
        })
      ),
    [
      "frontal types",
      "frontal types --out types/frontal.d.ts",
      "frontal types --env staging --json",
    ]
  );
}
