#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get staged .ts files
STAGED_TS=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.tsx?$' || true)

if [ -n "$STAGED_TS" ]; then
  echo "$STAGED_TS" | xargs bunx --no -- biome check --no-errors-on-unmatched --files-ignore-unknown=true
fi
